name: Run daily visual testing
on: 
    push:
      branches:
        - 'main'
    schedule:
        - cron: "0 9 * * *"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    visual-test:
        runs-on: ubuntu-latest
        steps:
            - name: Set current date as env variable
              run: echo "NOW=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'

            - name: Install dependencies
              run: npm ci

            - name: Run test
              run: npm test

            - name: Store report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: backstop_data_${{ env.NOW }}
                path: backstop_data
                retention-days: 14